# 1 process per container (web, db, ...)
version: '3'
services:
  web:
      build: .
      ports:
        - "8080:3000"
  db:
    image: "mysql"
    environment:
      - MY_SQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/foo

  volumes:
    db-data:

# docker-compose up